{
 "title": "Wireline Stages",
 "time": { "from": "2020-01-25T20:22:17.279Z", "to": "2020-01-26T05:18:30.291Z" },
 "templating": {
  "list": [
   {
    "name": "stage_id",
    "query": "select distinct stage_id from stages"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Stages",
   "type": "stat",
   "description": "Total stage count in interval",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  id as value,\n  'stages' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch)\nORDER BY time_start_epoch ASC"
    }
   ]
  },
  {
   "title": "Total Duration ",
   "type": "stat",
   "description": "Total Duration in Hole",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  duration_total_minutes as value,\n  'Total Duration' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch)\nORDER BY time_start_epoch ASC"
    }
   ]
  },
  {
   "title": "Total Charge Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  type AS metric,\n  depth_shot as value\nFROM shots\nWHERE 1=1\n  and $__timeFilter(timestamp)\n  and type = 'charge'\n    \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Plug Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  type AS metric,\n  depth_shot as value\nFROM shots\nWHERE 1=1\n  and $__timeFilter(timestamp)\n  and type = 'plug'\n    \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Depth",
   "type": "stat",
   "description": "Total Depth in Interval",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  depth_max / 5280 as value,\n  'depth_max' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch)\nORDER BY time_start_epoch ASC"
    }
   ]
  },
  {
   "title": "Depth Vertical",
   "type": "stat",
   "description": "Total Depth in Interval",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  depth_vertical / 5280 as value,\n  'depth_vertical' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch)\nORDER BY time_start_epoch ASC"
    }
   ]
  },
  {
   "title": "Total Depth Lateral",
   "type": "stat",
   "description": "Total Depth Lateral",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  depth_lateral /5280 as value,\n  'depth_lateral' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch)\nORDER BY time_start_epoch ASC"
    }
   ]
  },
  {
   "title": "Charge Depth Distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  type AS metric,\n  depth_shot as value\nFROM shots\nWHERE 1=1\n  and $__timeFilter(timestamp)\n  and type = 'charge'\n    \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Plug Depth Distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  type AS metric,\n  depth_shot as value\nFROM shots\nWHERE 1=1\n  and $__timeFilter(timestamp)\n  and type = 'plug'\n    \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Stages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"measured_depth\"\n  and $__timeFilter(timestamp)\n    \nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"voltage\"\n  and $__timeFilter(timestamp)\n    \nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"line_tension\"\n  and $__timeFilter(timestamp)\n  \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "CCL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"measured_depth\"\n  and $__timeFilter(timestamp)\n    \nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"casing_collar_locator\"\n  and $__timeFilter(timestamp)\n    \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "StageID: $stage_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "stage_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Duration ",
     "type": "stat",
     "description": "Total Duration in Hole",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  duration_total_minutes as value,\n  'Total Duration' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch) and\n  stage_id = $stage_id\nORDER BY time_start_epoch ASC"
      }
     ]
    },
    {
     "title": "Total Depth",
     "type": "stat",
     "description": "Total Depth in Interval",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  depth_max as value,\n  'depth_max' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch)\n  and stage_id in ($stage_id)\nORDER BY time_start_epoch ASC"
      }
     ]
    },
    {
     "title": "Depth Vertical",
     "type": "stat",
     "description": "Total Depth in Interval",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  depth_vertical as value,\n  'depth_vertical' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch)\n  and stage_id in ($stage_id)\nORDER BY time_start_epoch ASC"
      }
     ]
    },
    {
     "title": "Depth Lateral",
     "type": "stat",
     "description": "Total Depth Lateral",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(time_start_epoch) as time_sec,\n  depth_lateral as value,\n  'depth_lateral' as metric\nFROM stages\nWHERE\n  $__unixEpochFilter(time_start_epoch) and\n  stage_id = $stage_id\nORDER BY time_start_epoch ASC"
      }
     ]
    },
    {
     "title": "Charge Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  s.timestamp AS \"time\",\n  s.type AS metric,\n  s.depth_shot as value\nFROM shots s\nWHERE 1=1\n  and $__timeFilter(s.timestamp)\n  and s.type = 'charge'\n  and s.stage_id = $stage_id\n    \nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Plug Depth",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  s.timestamp AS \"time\",\n  s.type AS metric,\n  s.depth_shot as value\nFROM shots s\nWHERE 1=1\n  and $__timeFilter(s.timestamp)\n  and s.type = 'plug'\n  and s.stage_id = $stage_id\n    \nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "CCL",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 5, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"measured_depth\"\n  and $__timeFilter(timestamp)\n    \nORDER BY timestamp"
      },
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"casing_collar_locator\"\n  and $__timeFilter(timestamp)\n    \nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Charge Depth Distribution",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  type AS metric,\n  depth_shot as value\nFROM shots\nWHERE 1=1\n  and $__timeFilter(timestamp)\n  and type = 'charge'\n  and stage_id in ($stage_id)\n    \nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Stages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "lengthft" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"measured_depth\"\n  and $__timeFilter(timestamp)\n   and timestamp between  FROM_UNIXTIME(\n    (select time_start_epoch \n    from stages as s\n    where 1 = 1  \n      and s.stage_id = $stage_id\n    ))\n  and FROM_UNIXTIME((\n    select time_end_epoch\n    from stages as s\n    where 1 = 1\n      and s.stage_id = $stage_id\n  ))\n    \nORDER BY timestamp"
      },
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"voltage\"\n  and $__timeFilter(timestamp)\n  and timestamp between  FROM_UNIXTIME(\n    (select time_start_epoch \n    from stages as s\n    where 1 = 1  \n      and s.stage_id = $stage_id\n    ))\n  and FROM_UNIXTIME((\n    select time_end_epoch\n    from stages as s\n    where 1 = 1\n      and s.stage_id = $stage_id\n  ))\n    \nORDER BY timestamp"
      },
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value as value\nFROM data\nWHERE 1=1\n  and metric = \"line_tension\"\n  and $__timeFilter(timestamp)\n  and timestamp between  FROM_UNIXTIME(\n    (select time_start_epoch \n    from stages as s\n    where 1 = 1  \n      and s.stage_id = $stage_id\n    ))\n  and FROM_UNIXTIME((\n    select time_end_epoch\n    from stages as s\n    where 1 = 1\n      and s.stage_id = $stage_id\n  ))\n  \nORDER BY timestamp"
      }
     ]
    }
   ]
  }
 ]
}